### ISSUE TITLE
Training does not function as described

### ISSUE THREAD

**Issue by lqtza** [debbiemarkslab/SeqDesign#1]
Hey folks! First, thanks for making this code and preprint available - it's some really cool work! Second, a bit of an issue, the described command for training according to the readme doesn't work. There are no positional arguments in `run_autoregressive_fr.py`. Even if one passed a fasta through to the DataHelperSignleFamily class that wouldn't do much--  fastas are currently glob'ed from a dataset directory. 

How is one supposed train with a new fasta?

I did some minor edits to work around this (which I'm happy to share), but I'm not sure if they'll have any downstream effects.

**Comment by aaronkollasch** [comment]
Hey Jeliazko! Thanks for bringing this to our attention. 

I'm creating a pull request that fixes the README (the `--dataset` arg was missing) and modifies DataHelperSingleFamily to check for a direct path to a fasta file before globbing.

We prefer the dataset directory as it allows us to keep things organized and use compact dataset names (e.g. `BLAT_ECOLX`), and for new users, the directory structure does get built if you download the example data. However, existing files generally shouldn't collide with the dataset namespace, and direct paths would help usability.

I'm also including changes to handle fasta files without sequence weights (using uniform weights for now) as the helper would error on those otherwise.

If you ran into any other snags or have other edits please feel free to suggest them.

**Comment by lqtza** [comment]
Wow! @aaronkollasch thanks for the rapid response! I'll test it out and let you know how it goes.

**Comment by aaronkollasch** [comment]
Thanks @lqtza, that would be great!

**Comment by aaronkollasch** [comment]
There was a second bug specifically for filenames ending in .fa which I've fixed (sorry about that). In testing, `run_autoregressive_fr --dataset <dataset>.fa` now works as described in the readme, so I have merged the PR. Thanks again for submitting the issue!
